name: Sync GitHub Repositories

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch repos
        run: |
          curl -H "Authorization: Bearer ${{ secrets.PRIVATE_REPOS_TOKEN }}" \
          https://api.github.com/users/lnavarroto/repos \
          > repos.json

      - name: Commit repos.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add repos.json
          git commit -m "update repos list" || echo "no changes"
          git push
